FROM node:11
LABEL maintainer Jalal Hejazi <jalal.hejazi@gmail.com>

# Create app directory
WORKDIR /usr/src/app

# Install app dependencies
COPY package*.json ./

RUN npm install --only=production

# Bundle app source
COPY . .

EXPOSE 1234
CMD ["npm", "run","start" ]